### ISSUE TITLE
v2.0-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-loader#14]
The following items are to be included with the next MAJOR release of the Auro WC-Generator, all PRs are to be from the feature branch to `v2.0-rc` branch.

- [ ] https://github.com/AlaskaAirlines/auro-loader/issues/13
- [ ] https://github.com/AlaskaAirlines/auro-loader/issues/10
- [ ] https://github.com/AlaskaAirlines/auro-loader/issues/4

**Comment by braven112** [comment]
Closing in favor of issues and milestones
