### ISSUE TITLE
auro-loader: use of deprecated @alaskaairux/webcorestylesheets@3.7.3

### ISSUE THREAD

**Issue by ftaylor-alaska** [AlaskaAirlines/auro-loader#20]
# General Support Request
This component has a dependency on a deprecated version of the wcss.

Please update from @alaskaairux/webcorestylesheets@3.7.3 to latest (@aurodesignsystem/webcorestylesheets@5.0.4 or later)

**Comment by blackfalcon** [comment]
Closing this issue. Duplicate of the following 

- https://github.com/AlaskaAirlines/auro-loader/issues/21#event-10841430158
