### ISSUE TITLE
auro-loader: support additional sizes xs and xxs

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-loader#7]
## Is your feature request related to a problem? Please describe.
auro-loader needs to support smaller sizes for use in small elements such as `auro-button`.

## Describe the solution you'd like
auro-loader should be able to scale all the way down to effectively appear inline with button text.

## Describe alternatives you've considered
Could force auro-loader to scale using CSS transforms but it would be preferred to implement decorators for all sizes.

**Comment by blackfalcon** [comment]
Please open a DRAFT PR with this feature branch.

**Comment by blackfalcon** [comment]
@jason please remember to update the labels when the work status changes.
